package com.example.React_back.Models;

public enum Departments {
    SOFTWARE_DEVELOPMENT,
    QUALITY_ASSURANCE,
    IT_SUPPORT,
    NETWORKING,
    HUMAN_RESOURCES,
    FINANCE,
    MARKETING,
    SALES,
    ADMINISTRATION,
    RESEARCH_AND_DEVELOPMENT,
    DEVOPS,
    DATA_ANALYTICS,
    PRODUCT_MANAGEMENT,
    CYBERSECURITY,
    CLOUD_ENGINEERING,
    ARTIFICIAL_INTELLIGENCE,
    UI_UX_DESIGN
}